version: '3'

services:
  database:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: main
    ports: [5432]
    volumes:
    - postgres_volume:/var/lib/postgresql/data

volumes:
  postgres_volume: